name: Generate release-artifacts

# on events
on:
  release:
    types: 
        - created

# workflow tasks
jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Generate build files
        uses: nv4re/go-cross-build@v1.69.0
        with:
            platforms: 'linux/amd64, darwin/amd64, windows/amd64'
            package: ""
            name: 'tiktok-scraper'
            compress: 'false'
            dest: 'dist'
      - name: Copy build-artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "./dist/*.tar.gz"